### ISSUE TITLE
footer needs responsive padding

### ISSUE THREAD

**Issue by clairefro** [amrschmitz/incorpus#40]
There's a breakpoint between desktop/tablet viewport sizes where padding is missing in the footer

![image](https://user-images.githubusercontent.com/9841162/76767040-55fe9580-676f-11ea-972d-90a6bf45e7d5.png)

**Comment by amrschmitz** [comment]
@clairefro should be solved [here](https://github.com/amrschmitz/incorpus/commit/87aeb37f6cf2c5dacc54de87f73a1f94d6ff504b). let me know your thoughts

**Comment by clairefro** [comment]
fixed by @amrschmitz
