### ISSUE TITLE
fix landing page console errors (2)

### ISSUE THREAD

**Issue by clairefro** [amrschmitz/incorpus#43]
- convert `class` to `className` in header.js component
![image](https://user-images.githubusercontent.com/9841162/76777900-51da7400-677f-11ea-8c4d-78226d71f0d9.png)

- fix typo in landing page video 'preload' prop
![image](https://user-images.githubusercontent.com/9841162/76777970-6b7bbb80-677f-11ea-933a-dfa1e45e38fd.png)

**Comment by amrschmitz** [comment]
👌

**Comment by clairefro** [comment]
appears to be fixed
